import express, { type NextFunction, type Request, type Response as ExpressResponse } from 'express';
import request from 'supertest';
import { describe, expect, it, vi } from 'vitest';
import { createAuditReadAdapter } from '../src/integrations/audit-read/index.js';
import { createOperatorAuditRouter } from '../src/operator-audit/index.js';

const iso = '2026-01-01T00:00:00.000Z'; const eventId = '550e8400-e29b-41d4-a716-446655440000'; const tenantId = '650e8400-e29b-41d4-a716-446655440000';
const event = { event_id: eventId, occurred_at: iso, actor_kind: 'operator', actor_key: 'user_operator', action: 'business.read', entity_type: 'business', entity_id: tenantId, support_grant_id: null, outcome: 'succeeded', request_id: 'req-1', redacted_summary: 'Viewed business' };
const response = (data: unknown, status = 200, contentType = 'application/json') => new Response(JSON.stringify(data), { status, headers: { 'content-type': contentType } });
const base = (fetchImpl: (input: string | URL, init?: RequestInit) => Promise<Response>) => ({ baseUrl: 'https://business.test', serviceAuth: async (requestId: string) => { expect(requestId).toBe('req-1'); return 'Bearer internal'; }, fetchImpl });

describe('audit read adapter', () => {
  it('maps filters, cursor, auth, and request ID to the upstream contract', async () => { const fetchImpl = vi.fn(async (url: string | URL, init?: RequestInit) => { const parsed = new URL(String(url)); expect(parsed.pathname).toBe('/internal/operator/v1/audit-events'); expect(parsed.searchParams.get('tenant_id')).toBe(tenantId); expect(parsed.searchParams.get('actor_kind')).toBe('operator'); expect(parsed.searchParams.get('action')).toBe('business.read'); expect(parsed.searchParams.get('entity_type')).toBe('business'); expect(parsed.searchParams.get('outcome')).toBe('succeeded'); expect(parsed.searchParams.get('occurred_from')).toBe(iso); expect(parsed.searchParams.get('occurred_to')).toBe('2026-01-02T00:00:00.000Z'); expect(parsed.searchParams.get('cursor_occurred_at')).toBe(iso); expect(parsed.searchParams.get('cursor_event_id')).toBe(eventId); expect(init?.headers).toEqual({ Accept: 'application/json', 'X-Request-ID': 'req-1', Authorization: 'Bearer internal' }); return response({ success: true, data: { items: [event], next_cursor: null } }); }); const adapter = createAuditReadAdapter(base(fetchImpl)); await expect(adapter.listAuditEvents({ filters: { tenant_id: tenantId, actor_kind: 'operator', action: 'business.read', entity_type: 'business', outcome: 'succeeded', occurred_from: iso, occurred_to: '2026-01-02T00:00:00.000Z' }, limit: 10, cursor: { occurredAt: iso, eventId }, requestId: 'req-1' })).resolves.toEqual({ items: [event], next_cursor: null }); });
  it('rejects private or malformed projections and maps failures safely', async () => { const extra = createAuditReadAdapter(base(async () => response({ success: true, data: { items: [{ ...event, secret: 'x' }], next_cursor: null } }))); await expect(extra.listAuditEvents({ filters: {}, limit: 10, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); const html = createAuditReadAdapter(base(async () => response('<html>', 200, 'text/html'))); await expect(html.listAuditEvents({ filters: {}, limit: 10, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); const failed = createAuditReadAdapter(base(async () => response({ secret: 'x' }, 500))); await expect(failed.listAuditEvents({ filters: {}, limit: 10, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
  it('composes with the operator audit route', async () => { const adapter = createAuditReadAdapter(base(async () => response({ success: true, data: { items: [event], next_cursor: null } }))); const app = express(); app.use((_req, res, next) => { res.locals.requestId = 'req-1'; next(); }); app.use('/api/v1', createOperatorAuditRouter(adapter, (_req, _res, next) => next(), { permissionMiddleware: () => (_req, _res, next) => next() })); app.use((error: unknown, _req: Request, res: ExpressResponse, _next: NextFunction) => { const e = error as { status?: number; code?: string; message?: string }; res.status(e.status ?? 500).json({ error: { code: e.code, message: e.message } }); }); const result = await request(app).get('/api/v1/audit-events?limit=10'); expect(result.status).toBe(200); expect(result.body.data.items).toEqual([event]); });
  it('preserves service authentication failures', async () => { const adapter = createAuditReadAdapter({ baseUrl: 'https://business.test', serviceAuth: async () => '' }); await expect(adapter.listAuditEvents({ filters: {}, limit: 10, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'OPERATOR_AUTH_UNAVAILABLE' }); });
  it('maps abort-driven timeouts to dependency unavailable', async () => { const adapter = createAuditReadAdapter({ ...base(async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(new Error('aborted'))))), timeoutMs: 250 }); await expect(adapter.listAuditEvents({ filters: {}, limit: 10, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
});
