import express, { type NextFunction, type Request, type Response as ExpressResponse } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createDirectoryReadAdapter } from '../src/integrations/directory-read/index.js';
import { createOperatorDirectoryRouter } from '../src/operator-directory/index.js';

const operatorId = '550e8400-e29b-41d4-a716-446655440000';
const activity = '2026-01-01T00:00:00.000Z';
const item = { operator_id: operatorId, display_name: 'Operator', role: 'platform_operator' as const, status: 'active' as const, last_activity_at: null, assigned_tenant_count: 0 };
const body = (data: unknown, status = 200, contentType = 'application/json') => new Response(JSON.stringify(data), { status, headers: { 'content-type': contentType } });
const options = (fetchImpl: (input: string | URL, init?: RequestInit) => Promise<Response>, serviceAuth: (requestId: string) => string | Promise<string> = async () => 'Bearer internal') => ({ baseUrl: 'https://business.test/', serviceAuth, fetchImpl: fetchImpl as typeof fetch });

describe('directory read adapter', () => {
  it('maps the exact path, filters, cursor fields, request ID, and auth', async () => {
    let seenUrl = ''; let seenInit: RequestInit | undefined;
    const adapter = createDirectoryReadAdapter(options(async (url, init) => { seenUrl = String(url); seenInit = init; return body({ success: true, data: { items: [item], next_cursor: null } }); }));
    await expect(adapter.listOperators({ filters: { role: 'platform_operator', status: 'active' }, limit: 10, cursor: { lastActivityAt: activity, operatorId }, requestId: 'req-1' })).resolves.toEqual({ items: [item], next_cursor: null });
    const parsed = new URL(seenUrl); expect(parsed.pathname).toBe('/internal/operator/v1/operators'); expect(parsed.searchParams.get('role')).toBe('platform_operator'); expect(parsed.searchParams.get('status')).toBe('active'); expect(parsed.searchParams.get('limit')).toBe('10'); expect(parsed.searchParams.get('cursor_last_activity_at')).toBe(activity); expect(parsed.searchParams.get('cursor_operator_id')).toBe(operatorId); expect(seenInit?.headers).toEqual({ Accept: 'application/json', 'X-Request-ID': 'req-1', Authorization: 'Bearer internal' });
  });
  it('omits the null activity cursor while retaining the operator cursor', async () => { let seenUrl = ''; const adapter = createDirectoryReadAdapter(options(async (url) => { seenUrl = String(url); return body({ success: true, data: { items: [item], next_cursor: null } }); })); await adapter.listOperators({ filters: {}, limit: 10, cursor: { lastActivityAt: null, operatorId }, requestId: 'req-1' }); const parsed = new URL(seenUrl); expect(parsed.searchParams.has('cursor_last_activity_at')).toBe(false); expect(parsed.searchParams.get('cursor_operator_id')).toBe(operatorId); });
  it('accepts valid pages and rejects extra or private fields', async () => { const valid = createDirectoryReadAdapter(options(async () => body({ success: true, data: { items: [item], next_cursor: null } }))); await expect(valid.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).resolves.toEqual({ items: [item], next_cursor: null }); const extra = createDirectoryReadAdapter(options(async () => body({ success: true, data: { items: [{ ...item, email: 'private@example.test' }], next_cursor: null } }))); await expect(extra.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); });
  it('maps malformed JSON and non-JSON responses to invalid response', async () => { const malformed = createDirectoryReadAdapter(options(async () => new Response('bad-json', { status: 200, headers: { 'content-type': 'application/json' } }))); await expect(malformed.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); const html = createDirectoryReadAdapter(options(async () => body('<html>', 200, 'text/html'))); await expect(html.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); });
  it('maps non-2xx and abort-driven timeout to dependency unavailable', async () => { const failed = createDirectoryReadAdapter(options(async () => body({ secret: 'hidden' }, 502))); await expect(failed.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); const timeout = createDirectoryReadAdapter({ ...options(async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(new Error('aborted')))),), timeoutMs: 250 }); await expect(timeout.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
  it('preserves auth failures from callback throws and invalid credentials', async () => { const thrown = createDirectoryReadAdapter(options(async () => body({}), async () => { throw new Error('secret'); })); await expect(thrown.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'OPERATOR_AUTH_UNAVAILABLE' }); const invalid = createDirectoryReadAdapter(options(async () => body({}), async () => '')); await expect(invalid.listOperators({ filters: {}, limit: 25, cursor: null, requestId: 'req-1' })).rejects.toMatchObject({ code: 'OPERATOR_AUTH_UNAVAILABLE' }); });
  it('composes with the operator directory route', async () => { const adapter = createDirectoryReadAdapter(options(async () => body({ success: true, data: { items: [item], next_cursor: null } }))); const app = express(); app.use((_req, res, next) => { res.locals.requestId = 'req-1'; next(); }); app.use('/api/v1', createOperatorDirectoryRouter(adapter, (_req, _res, next) => next(), { permissionMiddleware: () => (_req, _res, next) => next() })); app.use((error: unknown, _req: Request, res: ExpressResponse, _next: NextFunction) => { const e = error as { status?: number; code?: string; message?: string }; res.status(e.status ?? 500).json({ error: { code: e.code, message: e.message } }); }); const result = await request(app).get('/api/v1/operators?role=platform_operator&limit=10'); expect(result.status).toBe(200); expect(result.body.data.items).toEqual([item]); });
});
