import { describe, expect, it } from 'vitest';
import express, { type NextFunction, type Request as ExpressRequest, type Response as ExpressResponse } from 'express';
import request from 'supertest';
import { createOperationsReadAdapter } from '../src/integrations/operations-read/index.js';
import { createOperatorOperationsRouter } from '../src/operator-operations/index.js';
const id = '550e8400-e29b-41d4-a716-446655440000';
const job = { job_id: id, tenant_id: id, event_type: 'invoice.created', status: 'pending', attempts: 0, max_attempts: 3, available_at: '2026-01-01T00:00:00Z', lease_until: null, completed_at: null, safe_last_error: null, created_at: '2026-01-01T00:00:00Z' };
const response = (data: unknown) => new globalThis.Response(JSON.stringify({ success: true, data }), { status: 200, headers: { 'content-type': 'application/json' } });
describe('operations read adapter', () => {
  it('forwards auth, request id, filters and cursor and validates projection', async () => { let seen: globalThis.Request | undefined; const adapter = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: (rid) => { expect(rid).toBe('req-1'); return 'Bearer service'; }, fetchImpl: async (input, init) => { seen = new Request(input, init); return response({ items: [job], next_cursor: null }); } }); const result = await adapter.listJobs({ filters: { tenant_id: id, status: 'pending', available_from: '2025-01-01T00:00:00Z', available_to: '2026-01-01T00:00:00Z' }, limit: 25, cursor: { availableAt: '2024-01-01T00:00:00Z', id }, requestId: 'req-1' }); expect(result.items).toHaveLength(1); expect(new URL(seen!.url).pathname).toBe('/internal/operator/v1/jobs'); expect(seen?.headers.get('authorization')).toBe('Bearer service'); expect(seen?.headers.get('x-request-id')).toBe('req-1'); expect(new URL(seen!.url).searchParams.get('cursor_id')).toBe(id); });
  it('rejects extra fields and maps transport failures', async () => { const bad = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => 'Bearer x', fetchImpl: async () => response({ items: [{ ...job, secret: 'pii' }], next_cursor: null }) }); await expect(bad.listJobs({ filters: {}, limit: 25, cursor: null, requestId: 'req' })).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); const down = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => 'Bearer x', fetchImpl: async () => { throw new Error('timeout'); } }); await expect(down.listJobs({ filters: {}, limit: 25, cursor: null, requestId: 'req' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
  it('maps every notification filter and nullable accepted cursor', async () => { let url = ''; const notification = { delivery_id: id, tenant_id: id, outbox_id: id, channel: 'email', template_version: 'v1', status: 'queued', provider_message_id: null, accepted_at: null, delivered_at: null }; const adapter = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => 'Bearer x', fetchImpl: async (input) => { url = String(input); return response({ items: [notification], next_cursor: null }); } }); const result = await adapter.listNotifications({ filters: { tenant_id: id, status: 'queued', channel: 'email', accepted_from: '2025-01-01T00:00:00Z', accepted_to: '2026-01-01T00:00:00Z' }, limit: 10, cursor: { acceptedAt: null, deliveryId: id }, requestId: 'req' }); expect(result.items[0]!.delivery_id).toBe(id); expect(new URL(url).pathname).toBe('/internal/operator/v1/notifications'); const params = new URL(url).searchParams; expect(params.get('tenant_id')).toBe(id); expect(params.get('status')).toBe('queued'); expect(params.get('channel')).toBe('email'); expect(params.get('accepted_from')).toContain('2025'); expect(params.get('accepted_to')).toContain('2026'); expect(params.get('cursor_delivery_id')).toBe(id); expect(params.has('cursor_accepted_at')).toBe(false); });
  it('maps an abort timeout to dependency unavailable', async () => { const adapter = createOperationsReadAdapter({ baseUrl: 'https://business.test/', timeoutMs: 250, serviceAuth: () => 'Bearer x', fetchImpl: async (_input, init) => await new Promise<globalThis.Response>((_resolve, reject) => { init?.signal?.addEventListener('abort', () => reject(new Error('aborted')), { once: true }); }) }); await expect(adapter.listJobs({ filters: {}, limit: 25, cursor: null, requestId: 'req' })).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
  it('composes route, adapter, and internal client end to end', async () => { let seen: globalThis.Request | undefined; const adapter = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => 'Bearer composed', fetchImpl: async (input, init) => { seen = new Request(input, init); return response({ items: [job], next_cursor: null }); } }); const app = express(); app.use((_req, res, next) => { res.locals.requestId = 'compose-req'; next(); }); app.use('/api/v1', createOperatorOperationsRouter(adapter, (_req, _res, next) => next(), { permissionMiddleware: () => (_req, _res, next) => next() })); app.use((e: unknown, _req: ExpressRequest, res: ExpressResponse, _next: NextFunction) => res.status((e as { status?: number }).status ?? 500).json(e)); const result = await request(app).get('/api/v1/jobs?tenant_id=' + id + '&status=pending&limit=10'); expect(result.status).toBe(200); expect(result.body.data.items[0].job_id).toBe(id); expect(new URL(seen!.url).pathname).toBe('/internal/operator/v1/jobs'); expect(new URL(seen!.url).searchParams.get('tenant_id')).toBe(id); expect(new URL(seen!.url).searchParams.get('status')).toBe('pending'); expect(new URL(seen!.url).searchParams.get('limit')).toBe('10'); expect(seen!.headers.get('authorization')).toBe('Bearer composed'); expect(seen!.headers.get('x-request-id')).toBe('compose-req'); });
  it('rejects malformed envelopes, non-json, and non-2xx without leaking upstream text', async () => { const make = (fetchImpl: typeof fetch) => createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => 'Bearer x', fetchImpl }); const call = (a: ReturnType<typeof make>) => a.listNotifications({ filters: {}, limit: 25, cursor: null, requestId: 'req' }); await expect(call(make(async () => response({ nope: true })))).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); await expect(call(make(async () => new Response('secret upstream PII', { status: 200, headers: { 'content-type': 'text/plain' } })))).rejects.toMatchObject({ code: 'DEPENDENCY_INVALID_RESPONSE' }); await expect(call(make(async () => new Response('secret upstream PII', { status: 500, headers: { 'content-type': 'application/json' } })))).rejects.toMatchObject({ code: 'DEPENDENCY_UNAVAILABLE' }); });
  it('preserves internal auth-unavailable errors', async () => { const adapter = createOperationsReadAdapter({ baseUrl: 'https://business.test/', serviceAuth: () => '' }); await expect(adapter.listJobs({ filters: {}, limit: 25, cursor: null, requestId: 'req' })).rejects.toMatchObject({ code: 'OPERATOR_AUTH_UNAVAILABLE' }); });
});
