import express, { type NextFunction, type Request, type Response } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { AppError } from '../src/errors.js';
import { createOperatorSupportActivityRouter, encodeSupportActivityCursor, type SupportActivityPort } from '../src/operator-support-activity/index.js';

const tenantId = '11111111-1111-4111-8111-111111111111';
const grantId = '22222222-2222-4222-8222-222222222222';
const eventId = '33333333-3333-4333-8333-333333333333';
const iso = '2026-01-01T00:00:00.000Z';
const activity = { event_id: eventId, tenant_id: tenantId, occurred_at: iso, actor_kind: 'operator' as const, actor_key: 'operator_1', action: 'grant.revoke', entity_type: 'support_grant', entity_id: grantId, support_grant_id: grantId, outcome: 'succeeded' as const, request_id: 'req_test', redacted_summary: 'Grant revoked' };
function makePort(overrides: Partial<SupportActivityPort> = {}): SupportActivityPort { return { listSupportActivity: async () => ({ items: [activity], next_cursor: null }), ...overrides }; }
function makeApp(port: SupportActivityPort, permitted = true) { const app = express(); app.use((_req: Request, res: Response, next: NextFunction) => { res.locals.requestId = 'req_test'; next(); }); app.use('/api/v1', createOperatorSupportActivityRouter(port, (_req, _res, next) => next(), { permissionMiddleware: (permission) => (_req, _res, next) => { if (permission !== 'support.activity.read') return next(new AppError(500, 'BAD_PERMISSION', 'bad')); return permitted ? next() : next(new AppError(403, 'FORBIDDEN', 'You do not have permission to access this resource.')); } })); app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { const typed = error as { status?: number; code?: string; message?: string }; res.status(typed.status ?? 500).json({ error: { code: typed.code, message: typed.message } }); }); return app; }

describe('operator support activity routes', () => {
  it('passes the route request ID to the activity port', async () => { let received = ''; const port = makePort({ listSupportActivity: async ({ requestId }) => { received = requestId; return { items: [], next_cursor: null }; } }); await request(makeApp(port)).get('/api/v1/support-activity'); expect(received).toBe('req_test'); });
  it('returns safe validated activity and requires the dedicated permission', async () => { const response = await request(makeApp(makePort())).get('/api/v1/support-activity?tenant_id=' + tenantId + '&support_grant_id=' + grantId + '&outcome=succeeded'); expect(response.status).toBe(200); expect(response.body.data.items[0]).toEqual(activity); expect(response.headers['cache-control']).toBe('no-store'); expect((await request(makeApp(makePort(), false)).get('/api/v1/support-activity')).body.error.code).toBe('FORBIDDEN'); });
  it('rejects strict and invalid filters', async () => { for (const query of ['unknown=x', 'actor_kind=visitor', 'support_grant_id=bad', 'limit=101', 'occurred_from=2026-01-02T00:00:00Z&occurred_to=2026-01-01T00:00:00Z', 'occurred_from=2999-01-01T00:00:00Z']) expect((await request(makeApp(makePort())).get('/api/v1/support-activity?' + query)).body.error.code).toBe('VALIDATION_FAILED'); });
  it('binds opaque cursors to all normalized filters', async () => { const filters = { tenant_id: tenantId, support_grant_id: grantId, action: 'grant.revoke' }; const cursor = encodeSupportActivityCursor({ occurredAt: iso, eventId }, filters); const port = makePort({ listSupportActivity: async ({ cursor: received }) => { expect(received).toEqual({ occurredAt: iso, eventId }); return { items: [], next_cursor: null }; } }); expect((await request(makeApp(port)).get(`/api/v1/support-activity?tenant_id=${tenantId}&support_grant_id=${grantId}&action=grant.revoke&cursor=${cursor}`)).status).toBe(200); expect((await request(makeApp(makePort())).get(`/api/v1/support-activity?tenant_id=${tenantId}&support_grant_id=${grantId}&action=grant.other&cursor=${cursor}`)).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(makeApp(makePort())).get('/api/v1/support-activity?cursor=bad')).body.error.code).toBe('VALIDATION_FAILED'); });
  it('rejects future provider values, malformed shapes, secrets, and maps failures safely', async () => { expect((await request(makeApp(makePort({ listSupportActivity: async () => ({ items: [{ ...activity, secret: 'x' } as never], next_cursor: null }) }))).get('/api/v1/support-activity')).body.error.code).toBe('DEPENDENCY_UNAVAILABLE'); expect((await request(makeApp(makePort({ listSupportActivity: async () => ({ items: [{ ...activity, occurred_at: '2999-01-01T00:00:00.000Z' },], next_cursor: null }) }))).get('/api/v1/support-activity')).body.error.code).toBe('DEPENDENCY_UNAVAILABLE'); expect((await request(makeApp({ listSupportActivity: async () => { throw new Error('secret database detail'); } })).get('/api/v1/support-activity')).body.error).toEqual({ code: 'DEPENDENCY_UNAVAILABLE', message: 'The support activity read service is unavailable.' }); });
  it('fails closed when the service is unavailable', async () => { const response = await request(makeApp({ listSupportActivity: async () => { throw new AppError(503, 'DEPENDENCY_UNAVAILABLE', 'The support activity read service is unavailable.'); } })).get('/api/v1/support-activity'); expect(response.status).toBe(503); expect(response.body.error).toEqual({ code: 'DEPENDENCY_UNAVAILABLE', message: 'The support activity read service is unavailable.' }); });
});
