import express, { type NextFunction, type Request, type Response } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createOperatorReadRouter, encodeBusinessCursor, type ReadPort } from '../src/operator-read/index.js';

const tenantId = '11111111-1111-4111-8111-111111111111';
const iso = '2026-01-01T00:00:00.000Z';
const summary = { tenant_id: tenantId, business_name: 'Drezivo Shop', slug: 'drezivo-shop', status: 'active' as const, currency: 'PHP', timezone: 'Asia/Manila', created_at: iso, updated_at: iso, branch_count: 1, active_member_count: 1, subscription: null };
const detail = { tenant_id: tenantId, business_name: 'Drezivo Shop', slug: 'drezivo-shop', status: 'active' as const, currency: 'PHP', timezone: 'Asia/Manila', created_at: iso, updated_at: iso, branches: [{ branch_id: '22222222-2222-4222-8222-222222222222', name: 'Main', code: 'MAIN', status: 'active', timezone: 'Asia/Manila' }], membership_summary: { active_count: 1, invited_count: 0, suspended_count: 0 }, subscription: null, entitlement_summary: { capability_count: 2, overridden_capability_count: 0 } };
function makePort(overrides: Partial<ReadPort> = {}): ReadPort { return { overview: async () => ({ as_of: iso, businesses: { total: 1, by_status: [{ status: 'active', count: 1 }] }, subscriptions: { active: 1, trial: 0, grace: 0, past_due: 0 }, attention: { failed_jobs: 0, failed_notifications: 0, pending_support_grants: 0 }, recent_signups: [{ tenant_id: tenantId, business_name: 'Drezivo Shop', slug: 'drezivo-shop', status: 'active', created_at: iso }] }), listBusinesses: async () => ({ items: [summary], next_cursor: null }), getBusiness: async () => detail, ...overrides }; }
function makeApp(port: ReadPort) { const app = express(); app.use((_req: Request, res: Response, next: NextFunction) => { res.locals.requestId = 'req_test'; next(); }); app.use('/api/v1', createOperatorReadRouter(port, (_req, _res, next) => next(), { permissionMiddleware: () => (_req, _res, next) => next() })); app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { const typed = error as { status?: number; code?: string; message?: string }; return res.status(typed.status ?? 500).json({ error: { code: typed.code, message: typed.message } }); }); return app; }

describe('operator read routes', () => {
  it('denies routes when permission middleware is not supplied', async () => { const app = express(); app.use('/api/v1', createOperatorReadRouter(makePort(), (_req, _res, next) => next())); app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { const typed = error as { status?: number; code?: string }; return res.status(typed.status ?? 500).json({ error: { code: typed.code } }); }); expect((await request(app).get('/api/v1/overview')).body.error.code).toBe('FORBIDDEN'); });
  it('returns a validated overview and caps recent signups', async () => { const response = await request(makeApp(makePort())).get('/api/v1/overview'); expect(response.status).toBe(200); expect(response.body.success).toBe(true); expect(response.body.data.recent_signups).toHaveLength(1); expect(response.headers['cache-control']).toBe('no-store'); });
  it('rejects unknown filters and future timestamps', async () => { const app = makeApp(makePort()); expect((await request(app).get('/api/v1/businesses?status=unknown')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(app).get('/api/v1/businesses?plan_code=growth')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(app).get('/api/v1/overview?as_of=2999-01-01T00:00:00.000Z')).body.error.code).toBe('VALIDATION_FAILED'); });
  it('validates list and detail payloads', async () => { const app = makeApp(makePort()); expect((await request(app).get('/api/v1/businesses')).body.data.items[0].tenant_id).toBe(tenantId); expect((await request(app).get(`/api/v1/businesses/${tenantId}`)).body.data.branches).toHaveLength(1); });
  it('rejects malformed UUIDs and returns safe not found', async () => { const app = makeApp(makePort({ getBusiness: async () => null })); expect((await request(app).get('/api/v1/businesses/not-a-uuid')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(app).get(`/api/v1/businesses/${tenantId}`)).body.error.code).toBe('NOT_FOUND'); });
  it('binds cursors to normalized filters', async () => { const filters = { status: ['active'] as const, sort: 'created_at_desc' as const }; const cursor = encodeBusinessCursor({ createdAt: iso, tenantId }, filters); const port = makePort({ listBusinesses: async ({ cursor: received }) => { expect(received).toEqual({ createdAt: iso, tenantId }); return { items: [], next_cursor: null }; } }); await request(makeApp(port)).get(`/api/v1/businesses?status=active&cursor=${encodeURIComponent(cursor)}`); const invalid = await request(makeApp(makePort())).get(`/api/v1/businesses?status=cancelled&cursor=${encodeURIComponent(cursor)}`); expect(invalid.body.error.code).toBe('VALIDATION_FAILED'); });
  it('maps unavailable reads to the canonical dependency error', async () => { const response = await request(makeApp({ ...makePort(), overview: async () => { throw new Error('database detail'); } })).get('/api/v1/overview'); expect(response.status).toBe(503); expect(response.body.error).toEqual({ code: 'DEPENDENCY_UNAVAILABLE', message: 'The business read service is unavailable.' }); });
});
