import express, { type NextFunction, type Request, type Response } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createOperatorOperationsRouter, encodeOperationsCursor, type OperationsPort } from '../src/operator-operations/index.js';

const tenant = '550e8400-e29b-41d4-a716-446655440000';
const job = { job_id: tenant, tenant_id: tenant, event_type: 'invoice.created', status: 'pending' as const, attempts: 0, max_attempts: 3, available_at: '2026-01-01T00:00:00Z', lease_until: null, completed_at: null, safe_last_error: null, created_at: '2026-01-01T00:00:00Z' };
const notification = { delivery_id: tenant, tenant_id: tenant, outbox_id: tenant, channel: 'email', template_version: 'v1', status: 'queued' as const, provider_message_id: null, accepted_at: null, delivered_at: null };
function app(port: OperationsPort, permission = (_name: string) => (_req: Request, _res: Response, next: NextFunction) => next()) { const a = express(); a.use((_req, res, next) => { res.locals.requestId = 'req'; next(); }); a.use('/api/v1', createOperatorOperationsRouter(port, (_req, _res, next) => next(), { permissionMiddleware: permission })); a.use((e: unknown, _req: Request, res: Response, _next: NextFunction) => { const x = e as { status?: number; code?: string; message?: string }; res.status(x.status ?? 500).json({ error: { code: x.code, message: x.message } }); }); return a; }
function port(overrides: Partial<OperationsPort> = {}): OperationsPort { return { listJobs: async () => ({ items: [job], next_cursor: null }), listNotifications: async () => ({ items: [notification], next_cursor: null }), ...overrides }; }

describe('operator operations read routes', () => {
  it('returns safe jobs and notifications with permissions and no-store', async () => { const seen: string[] = []; const r = await request(app(port(), (name) => { seen.push(name); return (_req, _res, next) => next(); })); expect((await r.get('/api/v1/jobs')).status).toBe(200); expect((await r.get('/api/v1/notifications')).body.data.items[0]).toEqual(notification); expect((await r.get('/api/v1/jobs')).headers['cache-control']).toBe('no-store'); expect(seen).toEqual(['job.read', 'notification.read']); });
  it('forwards the request id to both read port methods', async () => { let jobRequestId = ''; let notificationRequestId = ''; const p = port({ listJobs: async ({ requestId }) => { jobRequestId = requestId; return { items: [job], next_cursor: null }; }, listNotifications: async ({ requestId }) => { notificationRequestId = requestId; return { items: [notification], next_cursor: null }; } }); const r = request(app(p)); await r.get('/api/v1/jobs'); await r.get('/api/v1/notifications'); expect(jobRequestId).toBe('req'); expect(notificationRequestId).toBe('req'); });
  it('rejects unknown, array, invalid filters and cross-filter cursors', async () => { const r = request(app(port())); expect((await r.get('/api/v1/jobs?nope=x')).body.error.code).toBe('VALIDATION_FAILED'); expect((await r.get('/api/v1/jobs?status=wat')).body.error.code).toBe('VALIDATION_FAILED'); expect((await r.get('/api/v1/jobs?status=pending&status=leased')).body.error.code).toBe('VALIDATION_FAILED'); const c = encodeOperationsCursor({ availableAt: job.available_at, id: tenant }, { status: 'pending' }); expect((await r.get(`/api/v1/jobs?status=leased&cursor=${c}`)).body.error.code).toBe('VALIDATION_FAILED'); });
  it('rejects unsafe provider shapes, future records, and maps failures safely', async () => { const unsafe = port({ listJobs: async () => ({ items: [{ ...job, payload: 'secret' } as never], next_cursor: null }) }); expect((await request(app(unsafe)).get('/api/v1/jobs')).status).toBe(503); const future = port({ listNotifications: async () => ({ items: [{ ...notification, accepted_at: '2999-01-01T00:00:00Z' }], next_cursor: null }) }); expect((await request(app(future)).get('/api/v1/notifications')).status).toBe(503); const down = port({ listJobs: async () => { throw new Error('secret'); } }); expect((await request(app(down)).get('/api/v1/jobs')).body.error.code).toBe('DEPENDENCY_UNAVAILABLE'); });
});
