import express, { type NextFunction, type Request, type Response } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createOperatorBillingRouter, encodeSubscriptionCursor, type BillingReadPort } from '../src/operator-billing/index.js';

const tenantId = '550e8400-e29b-41d4-a716-446655440000';
const iso = '2026-01-01T00:00:00Z';
const summary = { tenant_id: tenantId, business_name: 'Shop', plan_code: 'starter' as const, status: 'active' as const, currency: 'PHP', current_period_start: iso, current_period_end: '2026-02-01T00:00:00Z', cancel_at_period_end: false };
const detail = { tenant_id: tenantId, plan_code: 'starter' as const, capability_count: 1, overridden_capability_count: 0, capabilities: [{ capability: 'reservations', enabled: true, limit_value: null }] };
function port(overrides: Partial<BillingReadPort> = {}): BillingReadPort { return { listSubscriptions: async () => ({ items: [summary], next_cursor: null }), getEntitlements: async () => detail, ...overrides }; }
function app(readPort: BillingReadPort, permission = (_name: string) => (_req: Request, _res: Response, next: NextFunction) => next()) { const a = express(); a.use((_req, res, next) => { res.locals.requestId = 'req'; next(); }); a.use('/api/v1', createOperatorBillingRouter(readPort, (_req, _res, next) => next(), { permissionMiddleware: permission })); a.use((e: unknown, _req: Request, res: Response, _next: NextFunction) => { const typed = e as { status?: number; code?: string; message?: string }; return res.status(typed.status ?? 500).json({ error: { code: typed.code, message: typed.message } }); }); return a; }

describe('operator billing read projections', () => {
  it('returns validated subscriptions, no-store, and routes permission', async () => { const seen: string[] = []; const r = await request(app(port(), (name) => { seen.push(name); return (_req, _res, next) => next(); })).get('/api/v1/subscriptions'); expect(r.status).toBe(200); expect(r.body.data.items[0]).toEqual(summary); expect(r.headers['cache-control']).toBe('no-store'); expect(seen).toContain('subscription.read'); });
  it('rejects invalid enums, unknown query keys, and cursor filter mismatch', async () => { expect((await request(app(port())).get('/api/v1/subscriptions?status=wat')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(app(port())).get('/api/v1/subscriptions?nope=x')).body.error.code).toBe('VALIDATION_FAILED'); const cursor = encodeSubscriptionCursor({ currentPeriodEnd: iso, tenantId }, { plan_code: 'starter' }); expect((await request(app(port())).get(`/api/v1/subscriptions?plan_code=business&cursor=${cursor}`)).body.error.code).toBe('VALIDATION_FAILED'); });
  it('rejects invalid tenant UUID and validates provider shapes', async () => { expect((await request(app(port())).get('/api/v1/businesses/nope/entitlements')).body.error.code).toBe('VALIDATION_FAILED'); const invalid = port({ getEntitlements: async () => ({ ...detail, capabilities: [{ capability: 'x', enabled: true, limit_value: 'secret' as never }] }) }); expect((await request(app(invalid)).get(`/api/v1/businesses/${tenantId}/entitlements`)).status).toBe(503); });
  it('returns safe not found and unavailable errors, and enforces permissions', async () => { const missing = port({ getEntitlements: async () => null }); expect((await request(app(missing)).get(`/api/v1/businesses/${tenantId}/entitlements`)).body.error.code).toBe('NOT_FOUND'); const denied = app(port(), () => (_req, _res, next) => next(Object.assign(new Error(), { status: 403, code: 'FORBIDDEN' }))); expect((await request(denied).get('/api/v1/subscriptions')).status).toBe(403); expect((await request(app({ listSubscriptions: async () => { throw new Error('down'); }, getEntitlements: async () => null })).get('/api/v1/subscriptions')).body.error.code).toBe('DEPENDENCY_UNAVAILABLE'); });
});
