import express, { type NextFunction, type Request, type Response } from 'express';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { AppError } from '../src/errors.js';
import { createOperatorAuditRouter, encodeAuditCursor, type AuditPort } from '../src/operator-audit/index.js';

const tenantId = '11111111-1111-4111-8111-111111111111';
const eventId = '22222222-2222-4222-8222-222222222222';
const iso = '2026-01-01T00:00:00.000Z';
const event = { event_id: eventId, occurred_at: iso, actor_kind: 'operator' as const, actor_key: 'operator_1', action: 'grant.revoke', entity_type: 'support_grant', entity_id: tenantId, support_grant_id: tenantId, outcome: 'succeeded' as const, request_id: 'req_test', redacted_summary: 'Grant revoked' };
function makePort(overrides: Partial<AuditPort> = {}): AuditPort { return { listAuditEvents: async () => ({ items: [event], next_cursor: null }), ...overrides }; }
function makeApp(port: AuditPort, permitted = true) { const app = express(); app.use((_req: Request, res: Response, next: NextFunction) => { res.locals.requestId = 'req_test'; next(); }); app.use('/api/v1', createOperatorAuditRouter(port, (_req, _res, next) => next(), { permissionMiddleware: () => (_req, _res, next) => permitted ? next() : next(new AppError(403, 'FORBIDDEN', 'You do not have permission to access this resource.')) })); app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { const typed = error as { status?: number; code?: string; message?: string }; res.status(typed.status ?? 500).json({ error: { code: typed.code, message: typed.message } }); }); return app; }

describe('operator audit routes', () => {
  it('passes the request ID to the audit port', async () => { let received = ''; const auditPort = makePort({ listAuditEvents: async ({ requestId }) => { received = requestId; return { items: [], next_cursor: null }; } }); await request(makeApp(auditPort)).get('/api/v1/audit-events'); expect(received).toBe('req_test'); });
  it('returns safe validated events and no-store', async () => { const response = await request(makeApp(makePort())).get('/api/v1/audit-events?tenant_id=' + tenantId + '&outcome=succeeded'); expect(response.status).toBe(200); expect(response.body.data.items[0]).toEqual(event); expect(response.headers['cache-control']).toBe('no-store'); });
  it('enforces permission and strict filters', async () => { expect((await request(makeApp(makePort(), false)).get('/api/v1/audit-events')).body.error.code).toBe('FORBIDDEN'); expect((await request(makeApp(makePort())).get('/api/v1/audit-events?unknown=x')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(makeApp(makePort())).get('/api/v1/audit-events?outcome=maybe')).body.error.code).toBe('VALIDATION_FAILED'); expect((await request(makeApp(makePort())).get('/api/v1/audit-events?occurred_from=2026-01-02T00:00:00Z&occurred_to=2026-01-01T00:00:00Z')).body.error.code).toBe('VALIDATION_FAILED'); });
  it('binds opaque cursors to normalized filters and rejects malformed cursors', async () => { const filters = { tenant_id: tenantId, outcome: 'succeeded' as const }; const cursor = encodeAuditCursor({ occurredAt: iso, eventId }, filters); const port = makePort({ listAuditEvents: async ({ cursor: received }) => { expect(received).toEqual({ occurredAt: iso, eventId }); return { items: [], next_cursor: null }; } }); expect((await request(makeApp(port)).get(`/api/v1/audit-events?tenant_id=${tenantId}&outcome=succeeded&cursor=${cursor}`)).status).toBe(200); expect((await request(makeApp(makePort())).get('/api/v1/audit-events?cursor=bad')).body.error.code).toBe('VALIDATION_FAILED'); });
  it('rejects future filter-bound cursors before calling the audit port', async () => { const filters = { tenant_id: tenantId, outcome: 'succeeded' as const }; const cursor = encodeAuditCursor({ occurredAt: new Date(Date.now() + 60_000).toISOString(), eventId }, filters); let called = false; const port = makePort({ listAuditEvents: async () => { called = true; return { items: [], next_cursor: null }; } }); const response = await request(makeApp(port)).get(`/api/v1/audit-events?tenant_id=${tenantId}&outcome=succeeded&cursor=${cursor}`); expect(response.status).toBe(400); expect(response.body.error.code).toBe('VALIDATION_FAILED'); expect(called).toBe(false); });
  it('rejects unsafe provider shapes and maps dependency failures safely', async () => { expect((await request(makeApp(makePort({ listAuditEvents: async () => ({ items: [{ ...event, secret: 'x' } as never], next_cursor: null }) }))).get('/api/v1/audit-events')).body.error.code).toBe('DEPENDENCY_UNAVAILABLE'); expect((await request(makeApp({ listAuditEvents: async () => { throw new Error('db detail'); } })).get('/api/v1/audit-events')).body.error).toEqual({ code: 'DEPENDENCY_UNAVAILABLE', message: 'The audit read service is unavailable.' }); });
});
