import { z } from 'zod';
import { AppError } from '../../errors.js';
import { createInternalServiceClient, type InternalServiceClient } from '../../internal-service-client.js';
import { operatorDirectoryItemSchema, type OperatorDirectoryPort } from '../../operator-directory/index.js';
export type DirectoryReadAdapterOptions = { baseUrl: string; serviceAuth: (requestId: string) => string | Promise<string>; fetchImpl?: typeof fetch; timeoutMs?: number; allowInsecureTransport?: boolean };
const envelope = z.object({ success: z.literal(true), data: z.unknown(), request_id: z.string().min(1).optional() }).strict();
const page = z.object({ items: z.array(operatorDirectoryItemSchema), next_cursor: z.object({ lastActivityAt: z.string().datetime({ offset: true }).nullable(), operatorId: z.string().min(1) }).strict().nullable() }).strict();
const unavailable = () => new AppError(503, 'DEPENDENCY_UNAVAILABLE', 'The operator directory service is unavailable.');
const invalid = () => new AppError(503, 'DEPENDENCY_INVALID_RESPONSE', 'The operator directory service returned an invalid response.');
export function createDirectoryReadAdapter(options: DirectoryReadAdapterOptions): OperatorDirectoryPort { if (!options.serviceAuth) throw unavailable(); let client: InternalServiceClient; try { client = createInternalServiceClient(options); } catch { throw unavailable(); } return { listOperators: async ({ filters, limit, cursor, requestId }) => { const params = new URLSearchParams({ limit: String(limit) }); if (filters.role) params.set('role', filters.role); if (filters.status) params.set('status', filters.status); if (cursor?.lastActivityAt !== null && cursor?.lastActivityAt !== undefined) params.set('cursor_last_activity_at', cursor.lastActivityAt); if (cursor) params.set('cursor_operator_id', cursor.operatorId); try { const response = await client.requestJsonResponse<unknown>(`/internal/operator/v1/operators?${params.toString()}`, { requestId }, [200]); if (response.data === null) throw unavailable(); const outer = envelope.safeParse(response.data); if (!outer.success) throw invalid(); const parsed = page.safeParse(outer.data.data); if (!parsed.success) throw invalid(); return parsed.data; } catch (e) { if (e instanceof AppError && ['DEPENDENCY_INVALID_RESPONSE', 'DEPENDENCY_UNAVAILABLE', 'OPERATOR_AUTH_UNAVAILABLE'].includes(e.code)) throw e; throw unavailable(); } } }; }
